defaults:
  - model: 1GB
  - filelike-impl: adlfs
  - write-method: write
  - block-size: 50MiB
  - _self_

blob:
  account: os.getenv("AZURE_STORAGE_ACCOUNT_NAME")
  container: models
  sas-env-var: AZURE_STORAGE_SAS_TOKEN

num-runs: 1

hydra:
  sweeper:
    params:
      filelike-impl: adlfs
      num-runs: 5
      write-method: write
      model: 5KiB-model,100KiB-model,100MiB-model,1GiB-model,5GiB-model
      block-size: 1KiB