defaults:
  - model: 1GB
  - filelike-impl: adlfs
  - read-method: read
  - block-size: 50MiB
  - _self_

blob:
  account: os.getenv("AZURE_STORAGE_ACCOUNT_NAME")
  container: models
  sas-env-var: AZURE_STORAGE_SAS_TOKEN

num-runs: 1

hydra:
  sweeper:
    params:
      filelike-impl: adlfs
      num-runs: 5
      read-method: read,torch-load
      model: 5KB-model,100KB-model,100MB-model,1GB-model,5GB-model
      block-size: 1KiB